const walkerImage1 =
  "https://media.licdn.com/dms/image/D4D03AQEfzyneqdEzLg/profile-displayphoto-shrink_800_800/0/1665425697970?e=2147483647&v=beta&t=WoUnEAdkV5redn5-Zx4rqayYduHxE647VhCZ6tIAzL8";
const walkerImage2 =
  "https://i.scdn.co/image/ab6761610000517420445c2cc9d93a550e1488b0";

const walkersMock = [
  {
    id: 1,
    name: "Lucas",
    lastName: "Zibaitis",
    address: "Sarachaga 4632",
    image: walkerImage1,
    dogCapacity: 3,
    walkDuration: 15,
    dogSize: "small",
  },
  {
    id: 2,
    name: "German",
    lastName: "Torres",
    address: "Aranguren 1020",
    image: walkerImage1,
    dogCapacity: 7,
    walkDuration: 30,
    dogSize: "medium",
  },
  {
    id: 3,
    name: "Victoria",
    lastName: "Correas",
    address: "Juan B. Justo 302",
    image: walkerImage2,
    dogCapacity: 1,
    walkDuration: 60,
    dogSize: "large",
  },
  {
    id: 4,
    name: "Alice",
    lastName: "Johnson",
    address: "Maple Street 123",
    image: walkerImage2,
    dogCapacity: 9,
    walkDuration: 15,
    dogSize: "small",
  },
  {
    id: 5,
    name: "John",
    lastName: "Smith",
    address: "Oak Avenue 456",
    image: walkerImage1,
    dogCapacity: 4,
    walkDuration: 30,
    dogSize: "medium",
  },
  {
    id: 6,
    name: "Emma",
    lastName: "Williams",
    address: "Pine Road 789",
    image: walkerImage2,
    dogCapacity: 8,
    walkDuration: 60,
    dogSize: "large",
  },
  {
    id: 7,
    name: "Daniel",
    lastName: "Miller",
    address: "Cedar Lane 567",
    image: walkerImage1,
    dogCapacity: 2,
    walkDuration: 15,
    dogSize: "small",
  },
  {
    id: 8,
    name: "Olivia",
    lastName: "Brown",
    address: "Birch Court 890",
    image: walkerImage1,
    dogCapacity: 6,
    walkDuration: 30,
    dogSize: "medium",
  },
  {
    id: 9,
    name: "Michael",
    lastName: "Davis",
    address: "Elm Place 234",
    image: walkerImage2,
    dogCapacity: 10,
    walkDuration: 60,
    dogSize: "large",
  },
  {
    id: 10,
    name: "Sophia",
    lastName: "Jackson",
    address: "Spruce Drive 567",
    image: walkerImage2,
    dogCapacity: 5,
    walkDuration: 15,
    dogSize: "small",
  },
];

export default walkersMock;
