const ownersData = [
  {
    username: "luciagonzalez",
    is_active: true,
    dogs: [
      {
        name: "Coco",
        breed: "Labrador",
        age: 3,
        img: "labrador2.jpg",
        size: "large",
        is_active: true,
      },
      {
        name: "Pulga",
        breed: "Poodle",
        age: 2,
        img: "poodle1.jpg",
        size: "small",
        is_active: true,
      },
      {
        name: "Charlie",
        breed: "Bulldog",
        age: 4,
        img: "bulldog1.jpg",
        size: "medium",
        is_active: true,
      },
    ],
  },
  {
    username: "marcelaalvarez",
    is_active: true,
    dogs: [
      {
        name: "Max",
        breed: "Labrador",
        age: 3,
        img: "labrador1.jpg",
        size: "medium",
        is_active: true,
      },
      {
        name: "Bella",
        breed: "Golden",
        age: 2,
        img: "golden1.jpg",
        size: "medium",
        is_active: true,
      },
      {
        name: "Betty",
        breed: "Chihuahua",
        age: 2,
        img: "chihuahua1.jpg",
        size: "small",
        is_active: true,
      },
      {
        name: "Molly",
        breed: "Beagle",
        age: 2,
        img: "beagle1.jpg",
        size: "small",
        is_active: true,
      },
      {
        name: "Hunter",
        breed: "Chihuahua",
        age: 2,
        img: "chihuahua3.jpg",
        size: "small",
        is_active: true,
      },
      {
        name: "Rubi",
        breed: "Huscky",
        age: 2,
        img: "husky1.jpg",
        size: "medium",
        is_active: true,
      },
    ],
  },
  {
    username: "marianagonzalez",
    is_active: true,
    dogs: [
      {
        name: "Max",
        breed: "Rottweiler",
        age: 3,
        img: "rottweiler1.jpg",
        size: "medium",
        is_active: true,
      },
      {
        name: "Bella",
        breed: "Golden",
        age: 2,
        img: "golden1.jpg",
        size: "medium",
        is_active: true,
      },
    ],
  },
  {
    username: "martinagarcia",
    is_active: true,
    dogs: [
      {
        name: "Coco",
        breed: "Labrador",
        age: 3,
        img: "labrador2.jpg",
        size: "large",
        is_active: true,
      },
      {
        name: "Pulga",
        breed: "Poodle",
        age: 2,
        img: "poodle1.jpg",
        size: "small",
        is_active: true,
      },
      {
        name: "Charlie",
        breed: "Bulldog",
        age: 4,
        img: "poodle1.jpg",
        size: "medium",
        is_active: true,
      },
    ],
  },
  {
    username: "martaperez",
    is_active: true,
    dogs: [
      {
        name: "Max",
        breed: "Labrador",
        age: 3,
        img: "labrador1.jpg",
        size: "medium",
        is_active: true,
      },
      {
        name: "Bella",
        breed: "Golden",
        age: 2,
        img: "golden1.jpg",
        size: "medium",
        is_active: true,
      },
    ],
  },
  {
    username: "nataliahernandez",
    is_active: true,
    dogs: [
      {
        name: "Max",
        breed: "Labrador",
        age: 3,
        img: "labrador1.jpg",
        size: "medium",
        is_active: true,
      },
      {
        name: "Bella",
        breed: "Golden",
        age: 2,
        img: "golden1.jpg",
        size: "medium",
        is_active: true,
      },
    ],
  },
  {
    username: "anamuhall",
    is_active: true,
    dogs: [
      {
        name: "Max",
        breed: "Labrador",
        age: 3,
        img: "labrador1.jpg",
        size: "medium",
        is_active: true,
      },
      {
        name: "Bella",
        breed: "Golden",
        age: 2,
        img: "golden1.jpg",
        size: "medium",
        is_active: true,
      },
    ],
  },
  {
    username: "juanlopez",
    is_active: true,
    dogs: [
      {
        name: "Daisy",
        breed: "Beagle",
        age: 1,
        img: "beagle1.jpg",
        size: "small",
        is_active: true,
      },
    ],
  },
  {
    username: "johndoe",
    is_active: true,
    dogs: [
      {
        name: "Rocky",
        breed: "Boxer",
        age: 3,
        img: "boxer1.jpg",
        size: "large",
        is_active: true,
      },
    ],
  },
  {
    username: "juangarcia",
    is_active: true,
    dogs: [
      {
        name: "Luna",
        breed: "Boxer",
        age: 4,
        img: "boxer1.jpg",
        size: "large",
        is_active: true,
      },
      {
        name: "Zeus",
        breed: "Rottweiler",
        age: 4,
        img: "rottweiler1.jpg",
        size: "large",
        is_active: true,
      },
      {
        name: "Coco",
        breed: "Chihuahua",
        age: 7,
        img: "chihuahua1.jpg",
        size: "small",
        is_active: true,
      },
      {
        name: "Ginger",
        breed: "Boxer",
        age: 4,
        img: "boxer1.jpg",
        size: "large",
        is_active: true,
      },
    ],
  },
  {
    username: "luisperez",
    is_active: true,
    dogs: [
      {
        name: "Shadow",
        breed: "Chihuahua",
        age: 1,
        img: "Chihuahua2.jpg",
        size: "small",
        is_active: true,
      },
    ],
  },
  {
    username: "juliogarcia",
    is_active: true,
    dogs: [
      {
        name: "Shadow",
        breed: "Chihuahua",
        age: 1,
        img: "Chihuahua3.jpg",
        size: "small",
        is_active: true,
      },
    ],
  },
];

module.exports = ownersData;
