const usersData = [
  //walkers
  {
    name: "Julia",
    lastName: "Smith",
    email: "julia.smith@woofer.com",
    password: "$2b$10$jBChsBNbIOCSWQC9gbHx1.aFLIAwpSggtpbaO4CPg1nhG39EAz5Xm",
    username: "janesmith",
    address: "456 Oak St",
    city: "Buenos Aires",
    province: "Buenos Aires",
    image: "pm00.jpg",
    location: null,
    isWalker: false,
    isOwner: false,
    is_active: true,
    score: 0,
    selectedType: "walker",
  },
  {
    name: "Sofía",
    lastName: "Lugat",
    email: "sofia.lugat@woofer.com",
    password: "$2b$10$jBChsBNbIOCSWQC9gbHx1.aFLIAwpSggtpbaO4CPg1nhG39EAz5Xm",
    username: "sofialugat",
    address: "Av. Cabildo 9012",
    city: "Buenos Aires",
    province: "Buenos Aires",
    image: "pm01.jpg",
    location: null,
    isWalker: false,
    isOwner: false,
    is_active: true,
    score: 0,
    selectedType: "walker",
  },
  {
    name: "Ana",
    lastName: "Pérez",
    email: "ana.perez@woofer.com",
    password: "$2b$10$jBChsBNbIOCSWQC9gbHx1.aFLIAwpSggtpbaO4CPg1nhG39EAz5Xm",
    username: "anaperez",
    address: "Calle San Martín 456",
    city: "Mendoza",
    province: "Mendoza",
    image: "pm03.jpg",
    location: null,
    isWalker: false,
    isOwner: false,
    is_active: true,
    score: 0,
    selectedType: "walker",
  },
  {
    name: "Sofía",
    lastName: "Rodríguez",
    email: "sofia.rodriguez@woofer.com",
    password: "$2b$10$jBChsBNbIOCSWQC9gbHx1.aFLIAwpSggtpbaO4CPg1nhG39EAz5Xm",
    username: "sofiarodriguez",
    address: "Calle San Luis 1011",
    city: "San Luis",
    province: "San Luis",
    image: "pm04.jpg",
    location: null,
    isWalker: false,
    isOwner: false,
    is_active: true,
    score: 0,
    selectedType: "walker",
  },
  {
    name: "Luisa",
    lastName: "Martín",
    email: "luisa.martin@woofer.com",
    password: "$2b$10$jBChsBNbIOCSWQC9gbHx1.aFLIAwpSggtpbaO4CPg1nhG39EAz5Xm",
    username: "luisamartin",
    address: "Calle San Martín 456",
    city: "City Bell",
    province: "Buenos Aires",
    image: "pm05.jpg",
    location: null,
    isWalker: false,
    isOwner: false,
    is_active: true,
    score: 0,
    selectedType: "walker",
  },
  {
    name: "Maria",
    lastName: "Gonzalez",
    email: "maria.gonzalez@woofer.com",
    password: "$2b$10$jBChsBNbIOCSWQC9gbHx1.aFLIAwpSggtpbaO4CPg1nhG39EAz5Xm",
    username: "mariagonzalez",
    address: "Calle 3 456",
    city: "La Plata",
    province: "Buenos Aires",
    image: "pm06.jpg",
    location: null,
    isWalker: false,
    isOwner: false,
    is_active: true,
    score: 0,
    selectedType: "walker",
  },
  {
    name: "Camila",
    lastName: "Herrera",
    email: "camila.herrera@woofer.com",
    password: "$2b$10$jBChsBNbIOCSWQC9gbHx1.aFLIAwpSggtpbaO4CPg1nhG39EAz5Xm",
    username: "camilaherrera",
    address: "Calle 4 456",
    city: "La Plata",
    province: "Buenos Aires",
    image: "pm07.jpg",
    location: null,
    isWalker: false,
    isOwner: false,
    is_active: true,
    score: 0,
    selectedType: "walker",
  },
  {
    name: "Fabiana",
    lastName: "Torres",
    email: "fabiana.torres@woofer.com",
    password: "$2b$10$jBChsBNbIOCSWQC9gbHx1.aFLIAwpSggtpbaO4CPg1nhG39EAz5Xm",
    username: "fabianatorres",
    address: "Calle 5 456",
    city: "La Plata",
    province: "Buenos Aires",
    image: "pm08.jpg",
    location: null,
    isWalker: false,
    isOwner: false,
    is_active: true,
    score: 0,
    selectedType: "walker",
  },
  {
    name: "Mariana",
    lastName: "Amodeo",
    email: "mariana.amodeo@woofer.com",
    password: "$2b$10$jBChsBNbIOCSWQC9gbHx1.aFLIAwpSggtpbaO4CPg1nhG39EAz5Xm",
    username: "marianaamodeo",
    address: "Calle 6 456",
    city: "La Plata",
    province: "Buenos Aires",
    image: "pm09.jpg",
    location: null,
    isWalker: false,
    isOwner: false,
    is_active: true,
    score: 0,
    selectedType: "walker",
  },
  {
    name: "Valentina",
    lastName: "Herrera",
    email: "valentina.herrera@woofer.com",
    password: "$2b$10$jBChsBNbIOCSWQC9gbHx1.aFLIAwpSggtpbaO4CPg1nhG39EAz5Xm",
    username: "valentinaherrera",
    address: "Calle 7 456",
    city: "La Plata",
    province: "Buenos Aires",
    image: "pm10.jpg",
    location: null,
    isWalker: false,
    isOwner: false,
    is_active: true,
    score: 0,
    selectedType: "walker",
  },
  {
    name: "Macarena",
    lastName: "Torres",
    email: "macarena.torres@woofer.com",
    password: "$2b$10$jBChsBNbIOCSWQC9gbHx1.aFLIAwpSggtpbaO4CPg1nhG39EAz5Xm",
    username: "macarenatorres",
    address: "Calle 8 456",
    city: "La Plata",
    province: "Buenos Aires",
    image: "pm11.jpg",
    location: null,
    isWalker: false,
    isOwner: false,
    is_active: true,
    score: 0,
    selectedType: "walker",
  },
  {
    name: "Emma",
    lastName: "Johnson",
    email: "emma.johnson@woofer.com",
    password: "$2b$10$jBChsBNbIOCSWQC9gbHx1.aFLIAwpSggtpbaO4CPg1nhG39EAz5Xm",
    username: "emmajohnson",
    address: "123 Main Street",
    city: "San Francisco",
    province: "Estados Unidos",
    image: "pm12.jpg",
    location: null,
    isWalker: false,
    isOwner: false,
    is_active: true,
    score: 0,
    selectedType: "walker",
  },
  {
    name: "Marcela",
    lastName: "Prosto",
    email: "marcela.prosto@woofer.com",
    password: "$2b$10$jBChsBNbIOCSWQC9gbHx1.aFLIAwpSggtpbaO4CPg1nhG39EAz5Xm",
    username: "marcelaprosto",
    image: "pm13.jpg",
    address: "Barrales 1423",
    city: "Lujan",
    province: "Buenos Aires",
    location: null,
    isWalker: false,
    isOwner: false,
    is_active: true,
    score: 0,
    selectedType: "walker",
  },
  {
    name: "Mariela",
    lastName: "Marreste",
    email: "mariela.marreste@woofer.com",
    password: "$2b$10$jBChsBNbIOCSWQC9gbHx1.aFLIAwpSggtpbaO4CPg1nhG39EAz5Xm",
    username: "marielamarreste",
    image: "pm14.jpg",
    address: "Barrales 1423",
    city: "Lujan",
    province: "Buenos Aires",
    location: null,
    isWalker: false,
    isOwner: false,
    is_active: true,
    score: 0,
    selectedType: "walker",
  },
  {
    name: "Carolina",
    lastName: "Murcega",
    email: "carolina.murcega@woofer.com",
    password: "$2b$10$jBChsBNbIOCSWQC9gbHx1.aFLIAwpSggtpbaO4CPg1nhG39EAz5Xm",
    username: "carolinamurcega",
    image: "pm15.jpg",
    address: "Barrales 1423",
    city: "Lujan",
    province: "Buenos Aires",
    location: null,
    isWalker: false,
    isOwner: false,
    is_active: true,
    score: 0,
    selectedType: "walker",
  },
  {
    name: "Martín",
    lastName: "Manrique",
    email: "martin.Manrique@woofer.com",
    password: "$2b$10$jBChsBNbIOCSWQC9gbHx1.aFLIAwpSggtpbaO4CPg1nhG39EAz5Xm",
    username: "martinmanrique",
    address: "Av. Rivadavia 3456",
    city: "Buenos Aires",
    province: "Buenos Aires",
    image: "ph00.jpg",
    location: null,
    isWalker: false,
    isOwner: false,
    is_active: true,
    score: 0,
    selectedType: "walker",
  },
  {
    name: "Carlos",
    lastName: "González",
    email: "carlos.gonzalez@woofer.com",
    password: "$2b$10$jBChsBNbIOCSWQC9gbHx1.aFLIAwpSggtpbaO4CPg1nhG39EAz5Xm",
    username: "carlosgonzalez",
    address: "Calle 9 de Julio 123",
    city: "Córdoba",
    province: "Córdoba",
    image: "ph01.jpg",
    location: null,
    isWalker: false,
    isOwner: false,
    is_active: true,
    score: 0,
    selectedType: "walker",
  },
  {
    name: "Ernesto",
    lastName: "Vedia",
    email: "ernesto.veda@woofer.com",
    password: "$2b$10$jBChsBNbIOCSWQC9gbHx1.aFLIAwpSggtpbaO4CPg1nhG39EAz5Xm",
    username: "ernestoveda",
    address: "Calle 9 de Julio 123",
    city: "Tucumán",
    province: "Tucumán",
    image: "ph02.jpg",
    location: null,
    isWalker: false,
    isOwner: false,
    is_active: true,
    score: 0,
    selectedType: "walker",
  },
  {
    name: "Lucio",
    lastName: "Gonzalez",
    email: "lucio.gonzalez@woofer.com",
    password: "$2b$10$jBChsBNbIOCSWQC9gbHx1.aFLIAwpSggtpbaO4CPg1nhG39EAz5Xm",
    username: "lucio.gonzalez",
    address: "Calle San Juan 1212",
    city: "Capital Federal",
    province: "Buenos Aires",
    image: "ph03.jpg",
    location: null,
    isWalker: false,
    isOwner: false,
    is_active: true,
    score: 0,
    selectedType: "walker",
  },
  {
    name: "Martín",
    lastName: "Fernández",
    email: "martin.fernandez@woofer.com",
    password: "$2b$10$jBChsBNbIOCSWQC9gbHx1.aFLIAwpSggtpbaO4CPg1nhG39EAz5Xm",
    username: "martinfernandez",
    address: "Calle San Juan 1212",
    city: "Capital Federal",
    province: "Buenos Aires",
    image: "ph04.jpg",
    location: null,
    isWalker: false,
    isOwner: false,
    is_active: true,
    score: 0,
    selectedType: "walker",
  },
  {
    name: "Fermin",
    lastName: "Francosi",
    email: "fermin.francosi@woofer.com",
    password: "$2b$10$jBChsBNbIOCSWQC9gbHx1.aFLIAwpSggtpbaO4CPg1nhG39EAz5Xm",
    username: "ferminfrancosi",
    address: "Calle San Juan 1212",
    city: "Capital Federal",
    province: "Buenos Aires",
    image: "ph05.jpg",
    location: null,
    isWalker: false,
    isOwner: false,
    is_active: true,
    score: 0,
    selectedType: "walker",
  },
  {
    name: "Mario",
    lastName: "Gonzalez",
    email: "mario.gonzalez@woofer.com",
    password: "$2b$10$jBChsBNbIOCSWQC9gbHx1.aFLIAwpSggtpbaO4CPg1nhG39EAz5Xm",
    username: "mario.gonzalez",
    address: "Calle San Juan 12",
    city: "Capital Federal",
    province: "Buenos Aires",
    image: "ph06.jpg",
    location: null,
    isWalker: false,
    isOwner: false,
    is_active: true,
    score: 0,
    selectedType: "walker",
  },
  {
    name: "Marcos",
    lastName: "Amancio",
    email: "marcos.amancio@woofer.com",
    password: "$2b$10$jBChsBNbIOCSWQC9gbHx1.aFLIAwpSggtpbaO4CPg1nhG39EAz5Xm",
    username: "marcosamancio",
    image: "ph07.jpg",
    address: "Calle Mendoza 1212",
    city: "Capital Federal",
    province: "Buenos Aires",
    location: null,
    isWalker: false,
    isOwner: false,
    is_active: true,
    score: 0,
    selectedType: "walker",
  },
  {
    name: "Pedro",
    lastName: "Mu;iz",
    email: "pedro.muz@woofer.com",
    password: "$2b$10$jBChsBNbIOCSWQC9gbHx1.aFLIAwpSggtpbaO4CPg1nhG39EAz5Xm",
    username: "pedromuz",
    image: "ph08.jpg",
    address: "Calle Mendoza 1212",
    city: "Capital Federal",
    province: "Buenos Aires",
    location: null,
    isWalker: false,
    isOwner: false,
    is_active: true,
    score: 0,
    selectedType: "walker",
  },
  {
    name: "Ernesto",
    lastName: "Milano",
    email: "ernesto.milano@woofer.com",
    password: "$2b$10$jBChsBNbIOCSWQC9gbHx1.aFLIAwpSggtpbaO4CPg1nhG39EAz5Xm",
    username: "ernestomilano",
    image: "ph09.jpg",
    address: "Calle Mendoza 1212",
    city: "Capital Federal",
    province: "Buenos Aires",
    location: null,
    isWalker: false,
    isOwner: false,
    is_active: true,
    score: 0,
    selectedType: "walker",
  },
  {
    name: "Juan Carlos",
    lastName: "Perez",
    email: "juan.carlos.perez@woofer.com",
    password: "$2b$10$jBChsBNbIOCSWQC9gbHx1.aFLIAwpSggtpbaO4CPg1nhG39EAz5Xm",
    username: "juan.carlos.perez",
    image: "ph10.jpg",
    address: "Calle Mendoza 1212",
    city: "Capital Federal",
    province: "Buenos Aires",
    location: null,
    isWalker: false,
    isOwner: false,
    is_active: true,
    score: 0,
    selectedType: "walker",
  },
  {
    name: "Roberto",
    lastName: "Martinez",
    email: "roberto.martinez@woofer.com",
    password: "$2b$10$jBChsBNbIOCSWQC9gbHx1.aFLIAwpSggtpbaO4CPg1nhG39EAz5Xm",
    username: "roberto.martinez",
    image: "ph11.jpg",
    address: "Calle Mendoza 1212",
    city: "Capital Federal",
    province: "Buenos Aires",
    location: null,
    isWalker: false,
    isOwner: false,
    is_active: true,
    score: 0,
    selectedType: "walker",
  },
  {
    name: "Cristian",
    lastName: "Fernandez",
    email: "cristian.fernandez@woofer.com",
    password: "$2b$10$jBChsBNbIOCSWQC9gbHx1.aFLIAwpSggtpbaO4CPg1nhG39EAz5Xm",
    username: "cristian.fernandez",
    image: "ph12.jpg",
    address: "Calle Mendoza 1212",
    city: "Capital Federal",
    province: "Buenos Aires",
    location: null,
    isWalker: false,
    isOwner: false,
    is_active: true,
    score: 0,
    selectedType: "walker",
  },
  {
    name: "MAriano",
    lastName: "Amat",
    email: "mariano.amat@woofer.com",
    password: "$2b$10$jBChsBNbIOCSWQC9gbHx1.aFLIAwpSggtpbaO4CPg1nhG39EAz5Xm",
    username: "mariano.amat",
    image: "ph13.jpg",
    address: "Calle Mendoza 1212",
    city: "Capital Federal",
    province: "Buenos Aires",
    location: null,
    isWalker: false,
    isOwner: false,
    is_active: true,
    score: 0,
    selectedType: "walker",
  },
  {
    name: "Miguel",
    lastName: "Sciorilli",
    email: "miguel.sciorilli@woofer.com",
    password: "$2b$10$jBChsBNbIOCSWQC9gbHx1.aFLIAwpSggtpbaO4CPg1nhG39EAz5Xm",
    username: "miguel.sciorilli",
    image: "ph14.jpg",
    address: "Calle Mendoza 1212",
    city: "Capital Federal",
    province: "Buenos Aires",
    location: null,
    isWalker: false,
    isOwner: false,
    is_active: true,
    score: 0,
    selectedType: "walker",
  },
  {
    name: "Miguel Angel",
    lastName: "Gutierrez",
    email: "miguel.angel.gutierrez@woofer.com",
    password: "$2b$10$jBChsBNbIOCSWQC9gbHx1.aFLIAwpSggtpbaO4CPg1nhG39EAz5Xm",
    username: "miguel.angel.gutierrez",
    image: "ph15.jpg",
    address: "Calle Mendoza 1212",
    city: "Capital Federal",
    province: "Buenos Aires",
    location: null,
    isWalker: false,
    isOwner: false,
    is_active: true,
    score: 0,
    selectedType: "walker",
  },
  {
    name: "Rodrigo",
    lastName: "Ovide",
    email: "rodrigo.ovide@woofer.com",
    password: "$2b$10$jBChsBNbIOCSWQC9gbHx1.aFLIAwpSggtpbaO4CPg1nhG39EAz5Xm",
    username: "rodrigo.ovide",
    image: "ph16.jpg",
    address: "Calle Mendoza 1212",
    city: "Capital Federal",
    province: "Buenos Aires",
    location: null,
    isWalker: false,
    isOwner: false,
    is_active: true,
    score: 0,
    selectedType: "walker",
  },
  {
    name: "Julian",
    lastName: "Dominguez",
    email: "julian.dominguez@woofer.com",
    password: "$2b$10$jBChsBNbIOCSWQC9gbHx1.aFLIAwpSggtpbaO4CPg1nhG39EAz5Xm",
    username: "julian.dominguez",
    image: "ph17.jpg",
    address: "Calle Mendoza 1212",
    city: "Capital Federal",
    province: "Buenos Aires",
    location: null,
    isWalker: false,
    isOwner: false,
    is_active: true,
    score: 0,
    selectedType: "walker",
  },
  {
    name: "Marcos",
    lastName: "Crespo",
    email: "marcos.crespo@woofer.com",
    password: "$2b$10$jBChsBNbIOCSWQC9gbHx1.aFLIAwpSggtpbaO4CPg1nhG39EAz5Xm",
    username: "marcos.crespo",
    image: "ph18.jpg",
    address: "Calle Mendoza 1212",
    city: "Capital Federal",
    province: "Buenos Aires",
    location: null,
    isWalker: false,
    isOwner: false,
    is_active: true,
    score: 0,
    selectedType: "walker",
  },
  {
    name: "Geronimo",
    lastName: "Miedes",
    email: "geronimo.miedes@woofer.com",
    password: "$2b$10$jBChsBNbIOCSWQC9gbHx1.aFLIAwpSggtpbaO4CPg1nhG39EAz5Xm",
    username: "geronimo.miedes",
    address: "Calle San Juan 1212",
    city: "Tucumán",
    province: "Tucumán",
    image: "ph19.jpg",
    location: null,
    isWalker: false,
    isOwner: false,
    is_active: true,
    score: 0,
    selectedType: "walker",
  },
  //Owners
  {
    name: "Lucía",
    lastName: "González",
    email: "lucia.gonzalez@woofer.com",
    password: "$2b$10$jBChsBNbIOCSWQC9gbHx1.aFLIAwpSggtpbaO4CPg1nhG39EAz5Xm",
    username: "luciagonzalez",
    address: "Av. Callao 6789",
    city: "Buenos Aires",
    province: "Buenos Aires",
    image: "om1.jpg",
    location: null,
    isWalker: false,
    isOwner: false,
    is_active: true,
    score: 0,
    selectedType: "owner",
  },
  {
    name: "Marcela",
    lastName: "Alvarez",
    email: "marcela.alvarez@woofer.com",
    password: "$2b$10$jBChsBNbIOCSWQC9gbHx1.aFLIAwpSggtpbaO4CPg1nhG39EAz5Xm",
    username: "marcelaalvarez",
    image: "om2.jpg",
    address: "Av. Callao 6789",
    city: "Buenos Aires",
    province: "Buenos Aires",
    location: null,
    isWalker: false,
    isOwner: false,
    is_active: true,
    score: 0,
    selectedType: "owner",
  },
  {
    name: "Mariana",
    lastName: "Gonzalez",
    email: "mariana.gonzalez@woofer.com",
    password: "$2b$10$jBChsBNbIOCSWQC9gbHx1.aFLIAwpSggtpbaO4CPg1nhG39EAz5Xm",
    username: "marianagonzalez",
    image: "om3.jpg",
    address: "Av. Callao 6789",
    city: "Buenos Aires",
    province: "Buenos Aires",
    location: null,
    isWalker: false,
    isOwner: false,
    is_active: true,
    score: 0,
    selectedType: "owner",
  },
  {
    name: "Martina",
    lastName: "Garcia",
    email: "martina.garcia@woofer.com",
    password: "$2b$10$jBChsBNbIOCSWQC9gbHx1.aFLIAwpSggtpbaO4CPg1nhG39EAz5Xm",
    username: "martinagarcia",
    image: "om4.jpg",
    address: "Av. Callao 6789",
    city: "Buenos Aires",
    province: "Buenos Aires",
    location: null,
    isWalker: false,
    isOwner: false,
    is_active: true,
    score: 0,
    selectedType: "owner",
  },
  {
    name: "Marta",
    lastName: "Perez",
    email: "marta.perez@woofer.com",
    password: "$2b$10$jBChsBNbIOCSWQC9gbHx1.aFLIAwpSggtpbaO4CPg1nhG39EAz5Xm",
    username: "martaperez",
    image: "om5.jpg",
    address: "Av. Callao 6789",
    city: "Buenos Aires",
    province: "Buenos Aires",
    location: null,
    isWalker: false,
    isOwner: false,
    is_active: true,
    score: 0,
    selectedType: "owner",
  },
  {
    name: "Natalia",
    lastName: "Hernandez",
    email: "natalia.hernandez@woofer.com",
    password: "$2b$10$jBChsBNbIOCSWQC9gbHx1.aFLIAwpSggtpbaO4CPg1nhG39EAz5Xm",
    username: "nataliahernandez",
    image: "om6.jpg",
    address: "Av. Callao 6789",
    city: "Buenos Aires",
    province: "Buenos Aires",
    location: null,
    isWalker: false,
    isOwner: false,
    is_active: true,
    score: 0,
    selectedType: "owner",
  },
  {
    name: "Ana",
    lastName: "Muhall",
    email: "ana.muhall@woofer.com",
    password: "$2b$10$jBChsBNbIOCSWQC9gbHx1.aFLIAwpSggtpbaO4CPg1nhG39EAz5Xm",
    username: "anamuhall",
    address: "Av. Corrientes 1234",
    city: "Buenos Aires",
    province: "Buenos Aires",
    image: "om7.jpg",
    location: null,
    isWalker: false,
    isOwner: false,
    is_active: true,
    score: 0,
    selectedType: "owner",
  },
  {
    name: "Juan",
    lastName: "Lopez",
    email: "juan.lopez@woofer.com",
    password: "$2b$10$jBChsBNbIOCSWQC9gbHx1.aFLIAwpSggtpbaO4CPg1nhG39EAz5Xm",
    username: "juanlopez",
    address: "Av. Santa Fe 5678",
    city: "Buenos Aires",
    province: "Buenos Aires",
    image: "oh1.jpg",
    location: null,
    isWalker: false,
    isOwner: false,
    is_active: true,
    score: 0,
    selectedType: "owner",
  },
  {
    name: "Juan",
    lastName: "Perez",
    email: "johndoe@woofer.com",
    password: "password123",
    username: "johndoe",
    address: "Sarmiento 651",
    city: "Ingeniero Jacobacci",
    province: "Rio Negro",
    image: "oh2.jpg",
    location: null,
    isWalker: false,
    isOwner: false,
    is_active: true,
    score: 0,
    selectedType: "owner",
  },

  {
    name: "Juan",
    lastName: "García",
    email: "juan.garcia@woofer.com",
    password: "$2b$10$jBChsBNbIOCSWQC9gbHx1.aFLIAwpSggtpbaO4CPg1nhG39EAz5Xm",
    username: "juangarcia",
    address: "Calle Belgrano 789",
    city: "Salta",
    province: "Salta",
    image: "oh3.jpg",
    location: null,
    isWalker: false,
    isOwner: false,
    is_active: false,
    score: 0,
    selectedType: "owner",
  },
  {
    name: "Luis",
    lastName: "Perez",
    email: "luis.perez@woofer.com",
    password: "$2b$10$jBChsBNbIOCSWQC9gbHx1.aFLIAwpSggtpbaO4CPg1nhG39EAz5Xm",
    username: "luisperez",
    image: "oh4.jpg",
    address: "Calle 8 789",
    city: "La Plata",
    province: "Buenos Aires",
    location: null,
    isWalker: false,
    isOwner: false,
    is_active: false,
    score: 0,
    selectedType: "owner",
  },
  {
    name: "Julio",
    lastName: "García",
    email: "julio.garcia@woofer.com",
    password: "$2b$10$jBChsBNbIOCSWQC9gbHx1.aFLIAwpSggtpbaO4CPg1nhG39EAz5Xm",
    username: "juliogarcia",
    image: "oh5.jpg",
    address: "Calle 8 789",
    city: "La Plata",
    province: "Buenos Aires",
    location: null,
    isWalker: false,
    isOwner: false,
    is_active: false,
    score: 0,
    selectedType: "owner",
  },
];

module.exports = usersData;
