const walkAndReviewsData = [
    {
      walkerUserName: "janesmith",
      ownerUserName: "anamuhall",
      date: new Date("2023-10-21"),
      startTime: new Date().toLocaleTimeString(),
      state: "Done",
      duration: "30",
      dogNumber: 1,
      totalPrice: 30,
      paymentMethod: "mercadopago",
      review: {
        type: "walker",
        score: 4,
        description: "The dog walker was very friendly and attentive to my dog.",
        date: "2023-10-28",
      },
    },
    {
      walkerUserName: "janesmith",
      ownerUserName: "marcelaalvarez",
      date: new Date("2023-10-21"),
      startTime: new Date().toLocaleTimeString(),
      state: "Done",
      duration: "30",
      dogNumber: 1,
      totalPrice: 30,
      paymentMethod: "mercadopago",
      review: {
        type: "walker",
        score: 1,
        description: "I was worried about leaving my dog with a stranger, but the walker put me at ease right away. They were great with my dog and I would definitely use their services again.",
        date: "2023-10-28",
      },
    },
    {
      walkerUserName: "janesmith",
      ownerUserName: "martinagarcia",
      date: new Date("2023-10-21"),
      startTime: new Date().toLocaleTimeString(),
      state: "Done",
      duration: "30",
      dogNumber: 1,
      totalPrice: 30,
      paymentMethod: "mercadopago",
      review: {
        type: "walker",
        score: 5,
        description: "I&apos;ve been using this dog walking service for a few months now and I couldn&apos;t be happier! The walkers are always on time and my dog loves them.",
        date: "2023-10-28",
      },
    },
    {
      walkerUserName: "janesmith",
      ownerUserName: "martinagarcia",
      date: new Date("2023-10-21"),
      startTime: new Date().toLocaleTimeString(),
      state: "Done",
      duration: "30",
      dogNumber: 1,
      totalPrice: 30,
      paymentMethod: "mercadopago",
      review: {
        type: "walker",
        score: 5,
        description: "I&apos;ve tried a few different dog walking services, but this one is by far the best. The walker is reliable and trustworthy, and my dog always comes back happy.",
        date: "2023-10-28",
      },
    },
    // 
    {
      walkerUserName: "janesmith",
      ownerUserName: "anamuhall",
      date: new Date("2023-11-21"),
      startTime: new Date().toLocaleTimeString(),
      state: "In progress",
      duration: "60",
      dogNumber: 3,
      totalPrice: 30,
      state: "Done",
      paymentMethod: "mercadopago",
    },
    {
      walkerUserName: "martinmanrique",
      ownerUserName: "anamuhall",
      date: new Date("2023-11-21"),
      startTime: new Date().toLocaleTimeString(),
      state: "Done",
      duration: "15",
      dogNumber: 2,
      totalPrice: 30,
      paymentMethod: "paypal",
      review: {
        type: "walker",
        score: 2,
        description:
          "The dog walker was late and didn&apos;t seem very interested in their job.",
        date: "2023-10-22",
      },
    },
    {
      walkerUserName: "martinmanrique",
      ownerUserName: "martaperez",
      date: new Date("2023-11-21"),
      startTime: new Date().toLocaleTimeString(),
      state: "Done",
      duration: "15",
      dogNumber: 2,
      totalPrice: 30,
      paymentMethod: "paypal",
      review: {
        type: "walker",
        score: 4,
        description:
          "I highly recommend this dog walking service! The walker is friendly, professional, and always goes above and beyond to make sure my dog is happy.",
        date: "2023-10-22",
      },
    },
    {
      walkerUserName: "martinmanrique",
      ownerUserName: "anamuhall",
      date: new Date(),
      startTime: new Date().toLocaleTimeString(),
      state: "In progress",
      duration: "15",
      dogNumber: 2,
      totalPrice: 30,
      paymentMethod: "paypal",
      review: {
        type: "walker",
        score: 2,
        description:
          "The dog walker was late and didn&apos;t seem very interested in their job.",
        date: "2023-10-22",
      },
    },
    {
      walkerUserName: "sofialugat",
      ownerUserName: "juanlopez",
      date: new Date("2023-10-20"),
      startTime: new Date().toLocaleTimeString(),
      state: "Done",
      duration: "60",
      dogNumber: 2,
      totalPrice: 30,
      paymentMethod: "paypal",
      review: {
        type: "walker",
        score: 5,
        description:
          "The dog walker was very professional and made sure my dog was comfortable at all times.",
        date: "2023-10-22",
      },
    },
    {
      walkerUserName: "carlosgonzalez",
      ownerUserName: "juangarcia",
      date: new Date("2023-10-10"),
      startTime: new Date().toLocaleTimeString(),
      state: "Done",
      duration: "15",
      dogNumber: 2,
      totalPrice: 30,
      paymentMethod: "paypal",
      review: {
        type: "walker",
        score: 1,
        description:
          "The dog walker didn&apos;t seem to have much experience and didn&apos;t know how to handle my dog.",
        date: "2023-10-11",
      },
    },
  
    {
      walkerUserName: "anaperez",
      ownerUserName: "juangarcia",
      date: new Date("2023-10-16"),
      startTime: new Date().toLocaleTimeString(),
      state: "Done",
      duration: "15",
      dogNumber: 2,
      totalPrice: 30,
      paymentMethod: "paypal",
      review: {
        type: "walker",
        score: 5,
        description:
          "The dog walker didn&apos;t seem to have much experience and didn&apos;t know how to handle my dog.",
        date: "2023-10-17",
      },
    },
  ];
  //   username: "sofiarodriguez",
  //   username: "martinfernandez",
  
  module.exports = walkAndReviewsData;
