const walkersData = [
  {
    username: "janesmith",
    dog_capacity: 1,
    walk_duration: ["60"],
    dog_size: ["medium"],
    is_available: true,
    schedule_availability: "",
    is_active: true,
    walk_types: [1],
    sale_details:
      "Having prior experience in dog care and a deep respect for their well-being, I can guarantee fun and safe walks for your four-legged friends. I am available to adapt to your specific schedules and needs. Let me take care of your furry friends while you fulfill your daily commitments!",
  },
  {
    username: "sofialugat",
    dog_capacity: 8,
    walk_duration: ["15"],
    dog_size: ["small"],
    is_available: true,
    schedule_availability: "",
    is_active: true,
    walk_types: [9],
    sale_details:
      "Are you looking for a reliable and friendly dog walker? Look no further! With years of experience caring for dogs, I can assure you that your dog will be in good hands. Call me today to schedule a walk!",
  },
  {
    username: "anaperez",
    dog_capacity: 8,
    walk_duration: ["15"],
    dog_size: ["small"],
    is_available: true,
    schedule_availability: "",
    is_active: true,
    walk_types: [9],
    sale_details:
      "Are you looking for a reliable and friendly dog walker? Look no further! With years of experience caring for dogs, I can assure you that your dog will be in good hands. Call me today to schedule a walk!",
  },
  {
    username: "sofiarodriguez",
    dog_capacity: 8,
    walk_duration: ["15"],
    dog_size: ["small"],
    is_available: true,
    schedule_availability: "",
    is_active: true,
    walk_types: [8, 9],
    sale_details:
      "Are you looking for a reliable and friendly dog walker? Look no further! With years of experience caring for dogs, I can assure you that your dog will be in good hands. Call me today to schedule a walk!",
  },
  {
    username: "luisamartin",
    dog_capacity: 8,
    walk_duration: ["15"],
    dog_size: ["small"],
    is_available: true,
    schedule_availability: "",
    is_active: true,
    walk_types: [3, 5],
    sale_details:
      "Are you looking for a reliable and friendly dog walker? Look no further! With years of experience caring for dogs, I can assure you that your dog will be in good hands. Call me today to schedule a walk!",
  },
  {
    username: "mariagonzalez",
    dog_capacity: 8,
    walk_duration: ["15"],
    dog_size: ["small"],
    is_available: true,
    schedule_availability: "",
    is_active: true,
    walk_types: [1, 2, 3, 4, 5, 6, 7, 8, 9],
    sale_details:
      "Are you looking for a reliable and friendly dog walker? Look no further! With years of experience caring for dogs, I can assure you that your dog will be in good hands. Call me today to schedule a walk!",
  },
  {
    username: "camilaherrera",
    dog_capacity: 8,
    walk_duration: ["15"],
    dog_size: ["small"],
    is_available: true,
    schedule_availability: "",
    walk_types: [1, 5, 9],
    is_active: true,
    walk_types: [1, 2, 3, 4, 5, 9],
    sale_details:
      "Are you looking for a reliable and friendly dog walker? Look no further! With years of experience caring for dogs, I can assure you that your dog will be in good hands. Call me today to schedule a walk!",
  },
  {
    username: "fabianatorres",
    dog_capacity: 8,
    walk_duration: ["15"],
    dog_size: ["small"],
    is_available: true,
    schedule_availability: "",
    is_active: true,
    walk_types: [1, 6, 7, 8, 9],
    sale_details:
      "Are you looking for a reliable and friendly dog walker? Look no further! With years of experience caring for dogs, I can assure you that your dog will be in good hands. Call me today to schedule a walk!",
  },
  {
    username: "marianaamodeo",
    dog_capacity: 8,
    walk_duration: ["15"],
    dog_size: ["small"],
    is_available: true,
    schedule_availability: "",
    is_active: true,
    walk_types: [1, 2, 3, 9],
    sale_details:
      "Are you looking for a reliable and friendly dog walker? Look no further! With years of experience caring for dogs, I can assure you that your dog will be in good hands. Call me today to schedule a walk!",
  },
  {
    username: "valentinaherrera",
    dog_capacity: 8,
    walk_duration: ["15"],
    dog_size: ["small"],
    is_available: true,
    schedule_availability: "",
    is_active: true,
    walk_types: [1, 2, 3, 4, 5, 6, 7, 8, 9],    
    sale_details:
      "Are you looking for a reliable and friendly dog walker? Look no further! With years of experience caring for dogs, I can assure you that your dog will be in good hands. Call me today to schedule a walk!",
  },
  {
    username: "macarenatorres",
    dog_capacity: 8,
    walk_duration: ["15"],
    dog_size: ["small"],
    is_available: true,
    schedule_availability: "",
    is_active: true,
    walk_types: [1, 2, 3, 4, 5, 6, 7, 8, 9],
    sale_details:
      "Are you looking for a reliable and friendly dog walker? Look no further! With years of experience caring for dogs, I can assure you that your dog will be in good hands. Call me today to schedule a walk!",
  },
  {
    username: "valentinaherrera",
    dog_capacity: 8,
    walk_duration: ["15"],
    dog_size: ["small"],
    is_available: true,
    schedule_availability: "",
    is_active: true,
    walk_types: [ 4, 5, 6, 7, 8, 9],
    sale_details:
      "Are you looking for a reliable and friendly dog walker? Look no further! With years of experience caring for dogs, I can assure you that your dog will be in good hands. Call me today to schedule a walk!",
  },
  {
    username: "marianaamodeo",
    dog_capacity: 8,
    walk_duration: ["15"],
    dog_size: ["small"],
    is_available: true,
    schedule_availability: "",
    is_active: true,
    walk_types: [1, 2, 3, 4, 5, 6, 7, 8, 9],
    sale_details:
      "Are you looking for a reliable and friendly dog walker? Look no further! With years of experience caring for dogs, I can assure you that your dog will be in good hands. Call me today to schedule a walk!",
  },
  {
    username: "valentinaherrera",
    dog_capacity: 8,
    walk_duration: ["15"],
    dog_size: ["small"],
    is_available: true,
    schedule_availability: "",
    is_active: true,
    walk_types: [1, 2, 3, 4, 5],
    sale_details:
      "Are you looking for a reliable and friendly dog walker? Look no further! With years of experience caring for dogs, I can assure you that your dog will be in good hands. Call me today to schedule a walk!",
  },
  {
    username: "macarenatorres",
    dog_capacity: 8,
    walk_duration: ["15"],
    dog_size: ["small"],
    is_available: true,
    schedule_availability: "",
    is_active: true,
    walk_types: [ 5, 6, 7, 8, 9],
    sale_details:
      "Are you looking for a reliable and friendly dog walker? Look no further! With years of experience caring for dogs, I can assure you that your dog will be in good hands. Call me today to schedule a walk!",
  },
  {
    username: "emmajohnson",
    dog_capacity: 3,
    walk_duration: ["60"],
    dog_size: ["small", "medium"],
    is_available: true,
    schedule_availability: "",
    is_active: true,
    walk_types: [1, 2, 3, 4, 5, 6, 7, 8, 9],
    sale_details:
      "Are you looking for a reliable and friendly dog walker? Look no further! With years of experience caring for dogs, I can assure you that your dog will be in good hands. Contact me today to schedule a walk!",
  },
  {
    username: "marcelaprosto",
    dog_capacity: 8,
    walk_duration: ["15"],
    dog_size: ["small"],
    is_available: true,
    schedule_availability: "",
    is_active: true,
    walk_types: [1, 2, 3, 4 ],
    sale_details:
      "Are you looking for a reliable and friendly dog walker? Look no further! With years of experience caring for dogs, I can assure you that your dog will be in good hands. Call me today to schedule a walk!",
  },
  {
    username: "marielamarreste",
    dog_capacity: 8,
    walk_duration: ["15"],
    dog_size: ["small"],
    is_available: true,
    schedule_availability: "",
    is_active: true,
    walk_types: [1, 2, 3],
    sale_details:
      "Are you looking for a reliable and friendly dog walker? Look no further! With years of experience caring for dogs, I can assure you that your dog will be in good hands. Call me today to schedule a walk!",
  },
  {
    username: "carolinamurcega",
    dog_capacity: 8,
    walk_duration: ["15"],
    dog_size: ["small"],
    is_available: true,
    schedule_availability: "",
    is_active: true,
    walk_types: [1, 2, 3, 4, 5, 6, 7, 8, 9],
    sale_details:
      "Are you looking for a reliable and friendly dog walker? Look no further! With years of experience caring for dogs, I can assure you that your dog will be in good hands. Call me today to schedule a walk!",
  },
  {
    username: "carlosgonzalez",
    dog_capacity: 4,
    walk_duration: ["60"],
    dog_size: ["medium"],
    is_available: true,
    schedule_availability: "",
    is_active: true,
    sale_details:
      "Do you need help taking care of your dog? Im here to help! As a dog walker, I can assure you that your dog will receive the exercise and attention they need. Call me today to schedule a walk!",
  },
  {
    username: "martinmanrique",
    dog_capacity: 5,
    walk_duration: ["30"],
    dog_size: ["small", "medium"],
    is_available: false,
    schedule_availability: "",
    is_active: true,
    walk_types: [1, 2, 3],
    sale_details:
      "Hello furry community! 👋 I am an animal enthusiast with a special love for dogs. I am excited to offer my dog walking services to those who need an extra hand to ensure that their adorable furry companions are happy and healthy.",
  },
  {
    username: "ernestoveda",
    dog_capacity: 4,
    walk_duration: ["30"],
    dog_size: ["medium"],
    is_available: true,
    schedule_availability: "",
    is_active: true,
    walk_types: [1],
    sale_details:
      "Are you tired of worrying about your dog’s exercise? Don’t worry anymore! As a dog walker, I can help keep your dog active and healthy. Contact me today to schedule a walk!",
  },
  {
    username: "lucio.gonzalez",
    dog_capacity: 10,
    walk_duration: ["60"],
    dog_size: ["small", "medium"],
    is_available: true,
    schedule_availability: "",
    is_active: false,
    walk_types: [1],
    sale_details:
      "Are you looking for a dog walker who can take care of your dog? Look no further! As a dog walker, I can help keep your dog healthy and happy. Contact me today to schedule a walk!",
  },
  {
    username: "martinfernandez",
    dog_capacity: 1,
    walk_duration: ["15"],
    dog_size: ["medium"],
    is_available: true,
    schedule_availability: "",
    is_active: false,
    walk_types: [1, 2, 3],
    sale_details:
      "Does your dog need more exercise? Look no further! As a dog walker, I can help keep your dog active and healthy. Call me today to schedule a walk!",
  },
  {
    username: "ferminfrancosi",
    dog_capacity: 8,
    walk_duration: ["15"],
    dog_size: ["small"],
    is_available: true,
    schedule_availability: "",
    is_active: true,
    walk_types: [1],
    sale_details:
      "Are you looking for a reliable and friendly dog walker? Look no further! With years of experience caring for dogs, I can assure you that your dog will be in good hands. Call me today to schedule a walk!",
  },
  {
    username: "mario.gonzalez",
    dog_capacity: 8,
    walk_duration: ["15"],
    dog_size: ["small"],
    is_available: true,
    schedule_availability: "",
    is_active: true,
    walk_types: [7, 8, 9],
    sale_details:
      "Are you looking for a reliable and friendly dog walker? Look no further! With years of experience caring for dogs, I can assure you that your dog will be in good hands. Call me today to schedule a walk!",
  },
  {
    username: "marcosamancio",
    dog_capacity: 8,
    walk_duration: ["15"],
    dog_size: ["small"],
    is_available: true,
    schedule_availability: "",
    is_active: true,
    walk_types: [1, 2, 3],
    sale_details:
      "Are you looking for a reliable and friendly dog walker? Look no further! With years of experience caring for dogs, I can assure you that your dog will be in good hands. Call me today to schedule a walk!",
  },
  {
    username: "pedromuz",
    dog_capacity: 8,
    walk_duration: ["15"],
    dog_size: ["small"],
    is_available: true,
    schedule_availability: "",
    is_active: true,
    walk_types: [1, 2, 3, 4, 5, 6, 7, 8, 9],
    sale_details:
      "Are you looking for a reliable and friendly dog walker? Look no further! With years of experience caring for dogs, I can assure you that your dog will be in good hands. Call me today to schedule a walk!",
  },
  {
    username: "ernestomilano",
    dog_capacity: 8,
    walk_duration: ["15"],
    dog_size: ["small"],
    is_available: true,
    schedule_availability: "",
    is_active: true,
    walk_types: [1],
    sale_details:
      "Are you looking for a reliable and friendly dog walker? Look no further! With years of experience caring for dogs, I can assure you that your dog will be in good hands. Call me today to schedule a walk!",
  },
  {
    username: "juan.carlos.perez",
    dog_capacity: 8,
    walk_duration: ["15"],
    dog_size: ["small"],
    is_available: true,
    schedule_availability: "",
    is_active: true,
    walk_types: [1],
    sale_details:
      "Are you looking for a reliable and friendly dog walker? Look no further! With years of experience caring for dogs, I can assure you that your dog will be in good hands. Call me today to schedule a walk!",
  },
  {
    username: "roberto.martinez",
    dog_capacity: 8,
    walk_duration: ["15"],
    dog_size: ["small"],
    is_available: true,
    schedule_availability: "",
    is_active: true,
    walk_types: [1],
    sale_details:
      "Are you looking for a reliable and friendly dog walker? Look no further! With years of experience caring for dogs, I can assure you that your dog will be in good hands. Call me today to schedule a walk!",
  },
  {
    username: "cristian.fernandez",
    dog_capacity: 8,
    walk_duration: ["15"],
    dog_size: ["small"],
    is_available: true,
    schedule_availability: "",
    is_active: true,
    walk_types: [1],
    sale_details:
      "Are you looking for a reliable and friendly dog walker? Look no further! With years of experience caring for dogs, I can assure you that your dog will be in good hands. Call me today to schedule a walk!",
  },
  {
    username: "mariano.amat",
    dog_capacity: 8,
    walk_duration: ["15"],
    dog_size: ["small"],
    is_available: true,
    schedule_availability: "",
    is_active: true,
    walk_types: [1],
    sale_details:
      "Are you looking for a reliable and friendly dog walker? Look no further! With years of experience caring for dogs, I can assure you that your dog will be in good hands. Call me today to schedule a walk!",
  },
  {
    username: "miguel.sciorilli",
    dog_capacity: 8,
    walk_duration: ["15"],
    dog_size: ["small"],
    is_available: true,
    schedule_availability: "",
    is_active: true,
    walk_types: [ 9],
    sale_details:
      "Are you looking for a reliable and friendly dog walker? Look no further! With years of experience caring for dogs, I can assure you that your dog will be in good hands. Call me today to schedule a walk!",
  },
  {
    username: "miguel.angel.gutierrez",
    dog_capacity: 8,
    walk_duration: ["15"],
    dog_size: ["small"],
    is_available: true,
    schedule_availability: "",
    is_active: true,
    walk_types: [1 ],
    sale_details:
      "Are you looking for a reliable and friendly dog walker? Look no further! With years of experience caring for dogs, I can assure you that your dog will be in good hands. Call me today to schedule a walk!",
  },
  {
    username: "rodrigo.ovide",
    dog_capacity: 8,
    walk_duration: ["15"],
    dog_size: ["small"],
    is_available: true,
    schedule_availability: "",
    is_active: true,
    walk_types: [1, 2, 3, 4, 5, 6, 7, 8, 9],
    sale_details:
      "Are you looking for a reliable and friendly dog walker? Look no further! With years of experience caring for dogs, I can assure you that your dog will be in good hands. Call me today to schedule a walk!",
  },
  {
    username: "julian.dominguez",
    dog_capacity: 8,
    walk_duration: ["15"],
    dog_size: ["small"],
    is_available: true,
    schedule_availability: "",
    is_active: true,
    walk_types: [1, 2, 3, 4, 5, 6, 7, 8, 9],
    sale_details:
      "Are you looking for a reliable and friendly dog walker? Look no further! With years of experience caring for dogs, I can assure you that your dog will be in good hands. Call me today to schedule a walk!",
  },
  {
    username: "marcos.crespo",
    dog_capacity: 8,
    walk_duration: ["15"],
    dog_size: ["small"],
    is_available: true,
    schedule_availability: "",
    is_active: true,
    walk_types: [1, 2, 3, 4, 5],
    sale_details:
      "Are you looking for a reliable and friendly dog walker? Look no further! With years of experience caring for dogs, I can assure you that your dog will be in good hands. Call me today to schedule a walk!",
  },
  {
    username: "geronimo.miedes",
    dog_capacity: 8,
    walk_duration: ["15"],
    dog_size: ["small"],
    is_available: true,
    schedule_availability: "",
    is_active: true,
    walk_types: [1, 2, 3, 4, 5, 6, 7, 8, 9],
    sale_details:
      "Are you looking for a reliable and friendly dog walker? Look no further! With years of experience caring for dogs, I can assure you that your dog will be in good hands. Call me today to schedule a walk!",
  },
];
module.exports = walkersData;
